version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    labels:
      - 'dependencies'
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel-plugin-*'
      eslint:
        patterns:
          - '@eslint/*'
          - 'eslint'
          - 'eslint-plugin-*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - 'react-is'
          - '@types/react'
          - '@types/react-dom'
          - '@types/react-is'
      rolldown:
        patterns:
          - '@rolldown/*'
          - 'rolldown'
          - 'rolldown-plugin-*'
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
      vitest:
        patterns:
          - '@vitest/*'
          - 'vitest'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 7
    labels:
      - 'dependencies'
