allowBuilds:
  cpu-features: true
  protobufjs: true
  sharp: true
  ssh2: true

dedupeInjectedDeps: false

minimumReleaseAge: 10080

packages:
  - 'benchmarks'
  - 'experiments'
  - 'packages/*'
  - 'scenarios/*'
  - 'website'

syncInjectedDepsAfterScripts:
  - build
