allowBuilds:
  cpu-features: true
  protobufjs: true
  sharp: true
  ssh2: true

minimumReleaseAge: 10080

overrides:
  nanoid: '3.3.16'

packages:
  - 'scenarios/*'
  - 'experiments'
  - 'packages/*'
  - 'website'
